[dh] added (ssl/tls) certificate support

diff --git a/.bin/download-helper b/.bin/download-helper
--- a/.bin/download-helper
+++ b/.bin/download-helper
@@ -8,6 +8,9 @@ cookie=$2
 # File to save $last
 last_path=$HOME/.download-helper
 
+# CA certificate directory
+ca_path="/etc/ssl/certs"
+
 # Get last directory downloaded to
 last=$(cat $last_path)
 
@@ -24,13 +27,25 @@ function runDmenu() {
 # first parameter: the cookie
 # second parameter: the url
 # third parameter: the local filename
-# FIXME: Certificate support
 function runCurl() {
   if [ $# -eq 2 ]; then
-    curl -kL --cookie-jar ${1} ${2} -O
+    curl -L --capath ${ca_path} --cookie-jar ${1} ${2} -O
   else
-    curl -kL --cookie-jar ${1} ${2} -o ${3}
+    curl -L --capath ${ca_path} --cookie-jar ${1} ${2} -o ${3}
   fi
+
+  # Verification of certificate failed
+  if [ $? -eq 60 ]; then
+      ans=$(echo -e "Yes\nNo" | dmenu $dmenu_conf -i -p "The verification of the certificate failed. Download without verification?")
+      if echo $ans | grep -i "^Yes" > /dev/null ; then
+          if [ $# -eq 2 ]; then
+              curl -kL --cookie-jar ${1} ${2} -O
+          else
+              curl -kL --cookie-jar ${1} ${2} -o ${3}
+          fi
+      fi
+  fi
+
   echo $PWD > $last_path
 }
 
