[unison-sync] clean up on termination

diff --git a/.bin/unison-sync b/.bin/unison-sync
--- a/.bin/unison-sync
+++ b/.bin/unison-sync
@@ -16,6 +16,9 @@ PROFILES=(
 TMP_NAME=tmp
 TMP_PROFILE=$HOME/.unison/$TMP_NAME.prf
 
+# Clean up on termination
+trap "rm ${TMP_PROFILE}" SIGINT SIGTERM SIGQUIT SIGKILL EXIT
+
 # If arguments are given PROFILES is ignored
 # and the arguments are used as profiles.
 if [ ! -z $1 ]; then
