[nixos/server] make job succeed independent of ssh return value

diff --git a/.github/workflows/cryptsetup-askpass.yml b/.github/workflows/cryptsetup-askpass.yml
--- a/.github/workflows/cryptsetup-askpass.yml
+++ b/.github/workflows/cryptsetup-askpass.yml
@@ -20,4 +20,5 @@ jobs:
       - shell: bash
         env:
           LUKS_PASSPHRASE: ${{ secrets.LUKS_PASSPHRASE }}
-        run: echo "$LUKS_PASSPHRASE" | ssh -i /home/runner/.ssh/id_rsa root@152.53.0.129 cryptsetup-askpass
+        # TODO: Make this step fail if the luks device could not be opened
+        run: echo "$LUKS_PASSPHRASE" | ssh root@152.53.0.129 cryptsetup-askpass || true
